Iter5
krasvl/metrics pull request #5
Opened 2024-12-01 16:51 UTC by krasvl

2024-12-04 09:37 UTC, s-shpak requested changes
1. Я не отмечаю все однотипные ошибки/замечания, исправь повторяющиеся проблемы самостоятельно, пожалуйста.

2. Любые вопросы по комментариям можно и нужно задавать в общем канале пачки

3. Добавь в проект линтер `golangci-lint`. Здесь объясняется как это сделать: https://github.com/s-shpak/praktikum-golangci-lint . Также добавь его проверки в `Github Actions` и исправь все замечания, пожалуйста

4. Не резолвь, пожалуйста, мои комментарии: мне нужно видеть, что именно мы обсуждали в повторном ревью. Если тебе хочется как-то трекать исправленные замечания, выставляй, например, реакции к комментариям

5. Дай мне, пожалуйста, права контрибьютора в репозитории, чтобы я мог резолвить комментарии, которые поправлены.

2024-12-04 09:37 UTC, s-shpak commented on cmd/agent/main.go
Постарайся оставлять в `main.go` (и в пакете `main`) как можно меньше логики: там могут лежать только создание и настройка компонентов и запуск сервиса. Всю остальную логику нужно перенести в `internal`. То есть в твоем случае необходимо инкапсулировать логику получения конфигурации

2024-12-04 09:37 UTC, s-shpak commented on cmd/agent/main.go
> +	addrenv := os.Getenv("ADDRESS")
Вместо `Getenv` лучше использовать `LookupEnv` (https://pkg.go.dev/os#LookupEnv) для того чтобы отличать пустую переменную окружения от необъявленной

2024-12-04 09:37 UTC, s-shpak commented on go.sum
Не забывай выполнять `go mod tidy` перед тем как пушить код в репозиторий (для этого можно настроить git-хуки)

2024-12-04 09:37 UTC, s-shpak commented on internal/agent/agent.go
> +		value, _ := a.storage.GetGauge(name)
Ошибки нужно проверять

2024-12-04 09:37 UTC, s-shpak commented on internal/agent/agent.go
> +	a.storage.SetCounter("PollCount", storage.Counter(1))
Счетчик количества сборов метрик должен увеличиваться на каждый сбор

2024-12-04 09:37 UTC, s-shpak commented on internal/handlers/handlers.go
> +	w.Write([]byte(fmt.Sprintf("%v", value)))
Для конвертации строк в числа и обратно используй пакет `strconv`. Он:
- позволяет более точно указывать параметры конвертации
- просто работает быстрее `fmt.Sprintf` из-за того, что не использует рефлексию

2024-12-04 09:37 UTC, s-shpak commented on internal/handlers/handlers.go
> +func (h *MetricsHandler) GetAllMetricsHandler(w http.ResponseWriter, r *http.Request) {
Для работы с `HTML` документами лучше использовать пакет html/template: https://pkg.go.dev/html/template

2024-12-04 09:37 UTC, s-shpak commented on internal/server/server_test.go
Если тестов пока нет, то этот файл можно удалить

2024-12-04 09:37 UTC, s-shpak commented on internal/storage/storage.go
> +type MetricsStorage interface {
В Go интерфейсы принято объявлять рядом с местом их использования: в одном пакете и, чаще всего, рядом с функцией/методом, которые их используют. Существуют исключения, но пока это не тот случай

2024-12-07 18:30 UTC, krasvl commented on internal/agent/agent.go
> +		value, _ := a.storage.GetGauge(name)
Это не ошибка, там возвращается (storage.Gauge, bool), как в обычной мапе
Проверки на существование ниже нет, т.к. выше получаются все доступные метрики и селектятся именно их значения
a.storage.GetAllGauges()

2024-12-07 18:33 UTC, krasvl commented on internal/agent/agent.go
> +	a.storage.SetCounter("PollCount", storage.Counter(1))
Он увеличивается, тут просто оборачивается 1 в storage.Counter
func (ms *MemStorage) SetCounter(name string, value Counter) {
	ms.counters[name] += value
}
Возможно не очевидное имя метода, но по аналогии с Gauge решил оставить Set

2024-12-09 09:20 UTC, s-shpak commented on internal/agent/agent.go
> +		value, _ := a.storage.GetGauge(name)
Ок, понял. Но мне не очень нравится, как именно это написано:
1. такая операция неконкурентнобезопасна
2. в будущем этот `bool` поменяется на `error` (когда начнем использовать реальную БД)

Почему бы не вернуть значения на строке 73 ?

2024-12-09 09:20 UTC, s-shpak commented on internal/agent/agent.go
> +	a.storage.SetCounter("PollCount", storage.Counter(1))
Понял. Это пока работает некрорректно: счетчик увеличивается при каждом сборе метрика на 1, а сервер прибалвяет полученное значение к пердыдущему. Вот пример того, что может произойти:

- агент собрал метрики 3 раза и отправляет серверу это значение
- сервер сохраняет его
- агент собрал метрики еще 2 раза и отправляет серверу значение 5 (3 + 2)
- сервер прибавляет его к предыдущему. С т.з. сервера агент произвел 8 сборов метрик

Подумай, как это исправить

2024-12-09 09:24 UTC, s-shpak requested changes

2024-12-09 09:24 UTC, s-shpak commented on internal/agent/agent.go
> +				return err
Кажется, что если агент не смог отправить метрики, то не стоит зваершать его выполнение

2024-12-09 09:24 UTC, s-shpak commented on internal/agent/agent_configure.go
> +	if value, exist := os.LookupEnv("ADDRESS"); exist && value != "" {
Если функция в Go возвращает вторую переменную булевого типа, которая указывает на корректность выполнения операции и т.п., ее принято называть `ok`.

2024-12-09 09:24 UTC, s-shpak commented on internal/handlers/handlers_test.go
> +			t.Errorf("Expected status %d, got %d", tt.expectedStatus, res.StatusCode)
Эта ошибка не завершит выполнение теста, но после нее нет смысла делать другие проверки. Так что после `t.Errorf` лучше вызвать `return`

2024-12-09 22:41 UTC, s-shpak commented on internal/agent/agent.go
> +				return err
`log.Fatal` приводит к завершению процесса

2024-12-09 22:42 UTC, s-shpak requested changes
См. последний комментарий

2024-12-12 19:11 UTC, s-shpak approved these changes

2025-01-07 17:43 UTC, merged